=== noise256/GameEngine_1/GameEngine_1/bin/xml/SectionDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="sd" xmlns:sd="sd" elementFormDefault="qualified">

<xs:element name="section_definition" />

<xs:element name="health" type="xs:integer" />

<xs:element name="section_name" type="xs:string" />

<xs:element name="texture_path" type="xs:string" />

<xs:complexType name="position">
	<xs:sequence>
		<xs:element name="x" type="xs:decimal"/>
		<xs:element name="y" type="xs:decimal"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="section_position">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="position" type="sd:position" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="dimension">
	<xs:sequence>
		<xs:element name="width" type="xs:integer"/>
		<xs:element name="height" type="xs:integer"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="texture_dimensions">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="dimension" type="sd:dimension" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="texture_vertex">
	<xs:sequence>
		<xs:element name="x" type="xs:decimal"/>
		<xs:element name="y" type="xs:decimal"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="texture_vertices">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="vertex" type="sd:texture_vertex" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== noise256/GameEngine_1/GameEngine_1/data/FrontArmourRightDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:section_definition xmlns:sd="sd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="sd SectionDefinition.xsd ">
	<sd:health>100</sd:health>
	<sd:section_name>front_armour_right</sd:section_name>
	<sd:texture_path>front_armour_right.png</sd:texture_path>
	<sd:section_position>
		<sd:position>
			<sd:x>186.5</sd:x>
			<sd:y>-62.5</sd:y>
		</sd:position>
	</sd:section_position>
	<sd:texture_dimensions>
		<sd:dimension>
			<sd:width>200</sd:width>
			<sd:height>125</sd:height>
		</sd:dimension>
	</sd:texture_dimensions>
	<sd:vertices>
		<sd:vertex>
			<sd:x>15.0</sd:x>
			<sd:y>0.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>15.0</sd:x>
			<sd:y>45.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>0.0</sd:x>
			<sd:y>55.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>0.0</sd:x>
			<sd:y>112.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>15.0</sd:x>
			<sd:y>125.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>30.0</sd:x>
			<sd:y>125.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>93.0</sd:x>
			<sd:y>77.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>93.0</sd:x>
			<sd:y>63.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>80.0</sd:x>
			<sd:y>55.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>80.0</sd:x>
			<sd:y>31.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>94.0</sd:x>
			<sd:y>20.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>185.0</sd:x>
			<sd:y>20.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>200.0</sd:x>
			<sd:y>10.0</sd:y>
		</sd:vertex>
		<sd:vertex>
			<sd:x>200.0</sd:x>
			<sd:y>0.0</sd:y>
		</sd:vertex>
	</sd:vertices>
</sd:section_definition>
